name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.Js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    
    - name: Get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'plugin.json'
        prop_path: 'Version'
    
    - name: Install dependencies
      run: |
        npm install
        zip -r Flow.Launcher.Plugin.Shortcut.zip . -x '*.git*'
    
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: 'Flow.Launcher.Plugin.Shortcut.zip'
        tag_name: "v${{steps.version.outputs.prop}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 